### ISSUE TITLE
问答时无法停止输出

### ISSUE THREAD

**Issue by JianXiao2021** [Xunzi-LLM-of-Chinese-classics/XunziALLM#11]
我下载了 Xunzi-Qwen2-1.5B（基座模型）到本地，并参考 [Qwen2 的命令行聊天 demo](https://github.com/QwenLM/Qwen2/blob/main/examples/demo/cli_demo.py)（将 DEFAULT_CKPT_PATH 改为本地模型路径）跟模型进行聊天。我发现模型回答的时候会一直输出，后面都是在重复相同的内容，无法停止。如下图所示：
![image](https://github.com/user-attachments/assets/b2ef1efb-e3b6-4c88-8b80-a7daf87b69e4)

之前有人提到在微调后有类似的问题：https://github.com/Xunzi-LLM-of-Chinese-classics/XunziALLM/issues/5 。但是我还没微调，只是直接使用 Xunzi-Qwen2-1.5B（基座模型）进行聊天。不知是不是模型本身问题？还是我的调用方式有问题？

**Comment by lclcjj** [comment]
这个是基座模型，没有进行过对齐。应该使用一些指令数据微调后再对话。
