### ISSUE TITLE
请问官方训练的时候，使用的是llama微调的吗，还是其他框架？

### ISSUE THREAD

**Issue by Idol-Dou2021** [Xunzi-LLM-of-Chinese-classics/XunziALLM#14]
尊敬的研发者，请问训练荀子chat大模型时，使用的是方案1还是方案2  ？
方案1：选择一个通用的基座模型，先训练一个垂直领域的大模型，然后使用训练得到的模型再次训练一个对话模型。
方案2：选择通用的基座模型1，单独训练一个垂直领域的大模型。选择指令基座模型2，单独训练一个chat模型。

**Comment by lclcjj** [comment]
是先使用通用基座，预训练得到一个古文基座模型，然后再微调这个古文基座训练出chat模型
