### ISSUE TITLE
咋感觉效果不行呢，很多事实性错误，是我的prompt写的不好吗

### ISSUE THREAD

**Issue by cristiano-xw** [Xunzi-LLM-of-Chinese-classics/XunziALLM#2]

**Comment by njauzzx** [comment]
在提问过程中，请尽可能详细地说明想要模型回答的内容
对于一些现实知识，由于训练数据局限性，且尚未经过人类反馈强化学习，幻觉现象仍然是不可避免的，如果想要实现知识问答，建议通过挂载知识库的形式进行
