### ISSUE TITLE
AttributeError: st.session_state has no attribute "history". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

### ISSUE THREAD

**Issue by liqinga** [Xunzi-LLM-of-Chinese-classics/XunziALLM#3]
AttributeError: st.session_state has no attribute "history". Did you forget to initialize it? More info: https://docs.streamlit.io/library/advanced-features/session-state#initialization

**Comment by njauzzx** [comment]
This may be related to your streamlit configuration, try changing the version?
